plugins {
    id 'application'
    id 'java'
}

group = 'ru.npi.kbju'
version = '3.0.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.13.4'
}

application {
    mainClass = 'ru.npi.kbju.Practice03App'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all']
}

tasks.withType(JavaExec).configureEach {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(25)
    }
    systemProperty 'file.encoding', 'UTF-8'
}

test {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'failed', 'skipped'
    }
}

tasks.register('preflight') {
    doLast {
        println "Проект: ${project.name}"
        println "Gradle: ${gradle.gradleVersion}"
        println "JVM Gradle: ${System.getProperty('java.version')}"
        println "ОС: ${System.getProperty('os.name')}"
    }
}
